#+begin_export latex
\section{Genom Runterladen}
Wir möchten das Genom von \emph{Mycoplasmoides genitalium}
untersuchen. Genauer gesagt, das Genom des \emph{Typstamms} von
\emph{M. genitalium}, G37. Dazu benötigen wir die Taxon-ID von
\emph{M. genitalium} G37. Die schauen wir mit dem Programm \ty{taxi}
in einer \emph{remoten} Datenbank nach, \ty{-r}, und finden 243273.
#+end_export
#+begin_src bash <<gene.sh>>=
  taxi -r "genitalium G37"
#+end_src
#+begin_export latex
\begin{verbatim}
# ID      Parent  Name
    243273  2097    Mycoplasmoides genitalium G37
\end{verbatim}
#+end_export
#+begin_export latex
Genome werden durch \emph{Accessions} identifiziert. Mit Hilfe der
Taxon-ID können wir die Accessions der Genome von \emph{M. genitalium}
G37 nachsehen. Dazu verwenden wir das Programm \ty{neighbors}, dem wir
als \emph{target} die Taxon-ID geben (\ty{-t}) und nur die Genome
dieser Targets anfordern (\emph{only}, \ty{-o}). Die Genome sollen
Qualitäts-\emph{Level} (\ty{-L}) \emph{complete} sein, und wir schauen
sie wieder in einer \emph{remoten} Datenbank nach (\ty{-r}). Wir
bekommen ein Genome angeboten, GCF\_000027325.1.
#+end_export
#+begin_src bash <<gene.sh>>=
  neighbors -t 243273 -o -L complete -r
#+end_src
#+begin_export latex
\small
\begin{verbatim}
# MRCA(targets): 243273, Mycoplasmoides genitalium G37
# MRCA(targets+neighbors): 243273, Mycoplasmoides genitalium G37
# Type  Taxon-ID  Name                           Genomes
t       243273    Mycoplasmoides genitalium G37  GCF_000027325.1
\end{verbatim}
\normalsize

Wir laden das eben gefundene Genom vom Netz mit dem Programm
\ty{datasets}, zusammen mit seinen Annotationen im sogenannten
GFF3-Format. Zu den Annotationen gehören insbesondere die Gene.
#+end_export
#+begin_src bash <<gene.sh>>=
  datasets download genome accession GCF_000027325.1 \
  	 --include genome,gff3
#+end_src
#+begin_export latex
Wir haben jetzt die gezippte, also komprimierte, Datei
\ty{ncbi\_dataset.zip} heruntergeladen.
#+end_export
#+begin_src bash <<gene.sh>>=
  ls
#+end_src
#+begin_export latex
Wir entzippen \ty{ncbi\_dataset.zip}.
#+end_export
#+begin_src bash <<gene.sh>>=
  unzip ncbi_dataset.zip
#+end_src
#+begin_export latex
Die neuen Daten liegen jetzt in einem Unter-Unterverzeichnis von
\ty{ncbi\_dataset}. Um die Eingabe langer Verzeichnisnamen zu
vereinfachen, kann man die Selbst-Ver\-voll\-stän\-di\-gung der Unix
Befehlszeile verwenden: Man tippt die ersten paar Buchstaben eines
Namens, gefolgt von \ty{Tab}. Wenn der Rest des Namens eindeutig ist,
wird er vervollständigt. Wenn nicht, bekommt man beim zweiten \ty{Tab}
die Möglichkeiten angezeigt.
#+end_export
#+begin_src bash <<gene.sh>>=
  ls ncbi_dataset/data/GCF_000027325.1/
#+end_src
#+begin_export latex
Um uns die Arbeit zu erleichtern, kopieren wir die beiden Dateien zu
Dateien mit einfacheren Namen mit dem Befehl \ty{cp} für
\emph{copy}. Er hat die Form \ty{cp von zu}. Zuerst kopieren wir das
Genom zu \ty{genom.fna}. Das Anhängsel \ty{fna} bedeutet Nukleotide im
FASTA Format. Das FASTA Format ist ein weitverbreitetes Format für
Sequenzen. Wir werden es gleich noch sehen.
#+end_export
#+begin_src bash <<gene.sh>>=
  cp ncbi_dataset/data/GCF_000027325.1/G*.fna genom.fna
#+end_src
#+begin_export latex
Dann die Annotationen zu \ty{annotation.gff}.
#+end_export
#+begin_src bash <<gene.sh>>=
  cp ncbi_dataset/data/GCF_000027325.1/genomic.gff annotation.gff
#+end_src
#+begin_export latex
\normalsize
Die beiden letzten Kopier-Befehle sahen sehr ähnlich aus. Da wäre es
nützlich, wenn wir einen alten Befehl leicht wiederholen könnten. Mit
den Pfeiltasten $\uparrow$ und $\downarrow$ könnten wir in der Liste
vergangener Befehle rauf und runter laufen.

\section{Die Genomdatei}
Als nächstes schauen wir uns den Kopf, \emph{head}, der Genomsequenz
an. Wir sehen das FASTA Format, das besteht aus einer Kopfzeile, die
mit \verb+>+ anfängt, und einer oder mehreren Zeilen mit Sequenzdaten.
#+end_export
#+begin_src bash <<gene.sh>>=
  head genom.fna
#+end_src
#+begin_export latex
\begin{verbatim}
>NC_000908.2 Mycoplasmoides genitalium G37, complete sequence
TAAGTTATTATTTAGTTAATACTTTTAACAATATTATTAAGGTATTTAAA...
...
\end{verbatim}
#+end_export
#+begin_export latex
Wie den Kopf der Datei, können wir uns auch ihr Ende, den
Schwanz, ansehen.
#+end_export
#+begin_src bash <<gene.sh>>=
  tail genom.fna
#+end_src
#+begin_export latex
\begin{verbatim}
...
TCAAGAATGACTTTTCGCCTTTCTGGACAAAGTTTAACCAATGATCCTGC...
GCCGCCTTTATTATTTACAAAAGAAATGATCATATATTTAAATGATTATA...
\end{verbatim}
Wir zählen die 580,076 Nukleotide im Genom von
\emph{M. genitalium}. Dabei sehen wir auch, dass etwa ein Drittel
seiner Basen jeweils \ty{A} und \ty{T} sind. Das ist deutlich mehr als
das Viertel, das wir bei Gleichverteilung der vier Basen erwarten
würden. Wir sagen, das Genom von \emph{M. genitalium} ist A/T-reich.
#+end_export
#+begin_src bash <<gene.sh>>=
  cres genom.fna
#+end_src
#+begin_export latex
\begin{verbatim}
Total: 580076
Residue Count  Fraction 
A       200544 0.346    
C       91515  0.158    
G       92306  0.159    
T       195711 0.337    
\end{verbatim}
#+end_export
#+begin_export latex
\section{Die Annotationsdatei}
Wir schauen uns die Annotationsdatei an, um herauszubekommen, wo in
ihr die Gene stehen. Dazu schauen uns zunächst wie beim Genom eben den
Kopf der Datei an, aber diesmal lassen wir uns die ersten 20 Zeilen
anzeigen (\ty{-n}) anstatt der ersten 10, die \ty{head} sonst
anzeigt. Nach den Kommentar-Zeilen mit Hash-Tag sehen wir eine
Tabelle.
#+end_export
#+begin_src bash <<gene.sh>>=
  head -n 20 annotation.gff
#+end_src
#+begin_export latex
Wir möchten nun die Kommentare wegschneiden. Dazu verwenden wir das
Programm \ty{grep}, mit dem die Zeilen ausgegeben werden, die mit
einem Muster übereinstimmen. Unser Muster ist ein Hashtag in der
ersten Position der Zeile.
#+end_export
#+begin_src bash <<gene.sh>>=
  grep '^#' annotation.gff
#+end_src
#+begin_export latex
Aber wir wollten doch die Kommentare \emph{weglassen}---jetzt haben
wir nur die Kommentare! Kein Problem, wir können mit \ty{-v} die Suche
invertieren, also die Zeilen ausgeben, die nicht mit Hashtag anfangen.
#+end_export
#+begin_src bash <<gene.sh>>=
  grep -v '^#' annotation.gff
#+end_src
#+begin_export latex
Die Tabelle hat neun Spalten, von denen die letzte aus viel Text
besteht. Also schneiden wir vom Ergebnis unseres \ty{grep} Befehls die
ersten 8 Spalten raus (\ty{cut}), und bekommen so eine
übersichtlichere Tabelle.
#+end_export
#+begin_src bash <<gene.sh>>=
  grep -v '^#' annotation.gff |
      cut -f 1-8
#+end_src
#+begin_export latex
\begin{verbatim}
NC_000908.2	RefSeq	region	1	580076	.	+	.
NC_000908.2	RefSeq	gene	686	1828	.	+	.
NC_000908.2	Protein Homology	CDS	686	1828...
...
\end{verbatim}

Wir haben eben die beiden Befehle \ty{grep} und \ty{cut} mit einem
senkrechten Strich verknüpft. Das können wir auf der Unix Befehlszeile
mit beliebigen Befehlen machen. Wenn wir allgemein schreiben
\begin{verbatim}
befehl1 | befehl2
\end{verbatim}
wird die Ausgabe von \ty{befehl1} die Eingabe von \ty{befehl2}. Man
spricht von einer ``Pipeline''. Wie eine echte Gas- oder Ölpipeline,
können wir eine Befehls\-pipeline beliebig verlängern. Zum Beispiel
können wir die Ausgabe des letzten Befehls mit \ty{head} auf seine
zehn Kopfzeilen reduzieren.
#+end_export
#+begin_src bash <<gene.sh>>=
  grep -v '^#' annotation.gff |
      cut -f 1-8 |
      head
#+end_src
#+begin_export latex
Die dritte Spalte unserer Tabelle zeigt den Typ der Annotation, wir
sehen \ty{region}, \ty{gene} und \ty{CDS}. CDS steht für \emph{coding
sequence}, also eine Sequenz, die ein Protein codiert. Wir schneiden
die Annotationen raus, sortieren sie (\ty{sort}), und zählen
(\emph{count}, \ty{-c}) die verschiedenen (\ty{unique})
Annotationen. Wir sehen, es gibt 546 Gene, von denen 524 Proteine
codieren. Es gibt auch 20 Pseudogene, das sind Gene, die nicht mehr
funktionieren---kaputte Gene.
#+end_export
#+begin_src bash <<gene.sh>>=
  grep -v '^#' annotation.gff |
      cut -f 3 |
      sort |
      uniq -c
#+end_src
#+begin_export latex
\begin{verbatim}
     524 CDS
     42 exon
    546 gene
     20 pseudogene
      1 region
      1 RNase_P_RNA
      3 rRNA
      1 SRP_RNA
      1 tmRNA
     36 tRNA
\end{verbatim}
#+end_export
#+begin_export latex
\section{Gene untersuchen}
Wir nehmen die Gene von \emph{M. genitalium} aus der Annotationsdatei,
indem wir mit \ty{grep} nach \emph{gene} suchen. Da \emph{pseudogene}
ebenfalls ein Treffer für \emph{gene} ist, entfernen wir im nächsten
Schritt die Pseudogene wieder.
#+end_export
#+begin_src bash <<gene.sh>>=
  cut -f 1-8 annotation.gff |
      grep gene |
      grep -v pseudogene
#+end_src
#+begin_export latex
\begin{verbatim}
NC_000908.2	RefSeq	gene	686	1828	.	+	.
...
\end{verbatim}
Wir vergewissern uns, dass wir die eben schon gezählten 546 Gene
haben, indem wir die Zeilen (\emph{lines}, \ty{-l}) in unserer Ausgabe
mit dem Programm \ty{wc} zählen. Der Name \ty{wc} steht für \emph{word
counter}.
#+end_export
#+begin_src bash <<gene.sh>>=
  cut -f 1-8 annotation.gff |
      grep gene |
      wc -l 
#+end_src
#+begin_export latex
Für die Darstellung von Genen gibt es drei wichtige Spalten in unserer
Tabelle:
\begin{itemize}
\item Spalte 4: Start Position
\item Spalte 5: End Position
\item Spalte 7: Strang der DNA-Doppelhelix, \ty{+} oder \ty{-}
\end{itemize}
Wir schneiden die drei wichtigen Spalten aus und lenken das Ergebnis
mit \verb+>+ in die Datei \ty{gene.txt}.
#+end_export
#+begin_src bash <<gene.sh>>=
  cut -f 1-8 annotation.gff |
      grep gene |
      cut -f 4,5,7 > gene.txt
#+end_src
#+begin_export latex
Wir schauen uns den Kopf von \ty{gene.txt} an.
#+end_export
#+begin_src bash <<gene.sh>>=
  head gene.txt
#+end_src
#+begin_export latex
\begin{verbatim}
686	1828	+
1828	2760	+
2845	4797	+
...
\end{verbatim}
Wir schneiden das erste Gen, also die Basen 686--1828, aus der
Genomsequenz. Was sind die ersten drei Basen des Gens? Weiß jemand
vielleicht, für welche Aminosäure die codieren?
#+end_export
#+begin_src bash <<gene.sh>>=
  cutSeq -r 686-1828 genom.fna
#+end_src
#+begin_export latex
\begin{verbatim}
>NC_000908.2 Mycoplasmoides genitalium G37, complete sequence...
ATGAAAATATTAATTAATAAAAGTGAATTGAATAAAATTTTGAAAAAAAT...
...
\end{verbatim}
Wir translatieren unser Gen und finden, dass seine erste Aminosäure
\ty{M} ist, Methionin, mit der Proteine normalerweise anfangen. Weiß
jemand, was die letzte Aminosäure in unserer Translation ist?
#+end_export
#+begin_src bash <<gene.sh>>=
  cutSeq -r 686-1828 genom.fna |
      translate
#+end_src
#+begin_export latex
\begin{verbatim}
>NC_000908.2 Mycoplasmoides genitalium G37... - translated
MKILINKSELNKILKKMNNVIISNNKIKPHHSYFLIEAKEKEINFYANNE...
...
INFDFQGNSKYFLITSKSEPELKQILVPSR*
\end{verbatim}
Jetzt untersuchen wir die Längen der Gene von
\emph{M. genitalium}. Dazu schreiben wir ein kleines Programm in der
Programmiersprache Awk. Awk geht zeilenweise vor, und in jeder Zeile
der Eingabe heißt der erste Wert \verb+$1+, der zweite \verb+$2+, und
so weiter. Bei uns ist der erste Wert die Anfangsposition des Gens,
der zweite Wert die Endposition. So können wir die Länge jedes Gens
als \ty{len} ausrechnen und drucken.
#+end_export
#+begin_src bash <<gene.sh>>=
  awk '{len=$2-$1+1; print len}' gene.txt |
      head
#+end_src
#+begin_export latex
\begin{verbatim}
1143
933
1953
...
\end{verbatim}
#+end_export
#+begin_export latex
Indem wir die Genlängen nummerisch (\ty{-n}) sortieren, finden wir das
kürzeste. Es besteht nur aus 74 Basen. Aber es ist nicht alleine, vier
weitere Gene bestehen ebenfalls aus nur 74 Basen.
#+end_export
#+begin_src bash <<gene.sh>>=
  awk '{l=$2-$1+1; print l}' gene.txt |
      sort -n |
      head
#+end_src
#+begin_export latex
\begin{verbatim}
74
74
74
74
74
75
...
\end{verbatim}
Das längste Gen is über 70-mal länger als die kürzesten und besteht
aus 5.418 Basen.
#+end_export
#+begin_src bash <<gene.sh>>=
  awk '{l=$2-$1+1; print l}' gene.txt |
      sort -n |
      tail
#+end_src
#+begin_export latex
\begin{verbatim}
3678
...
5418
\end{verbatim}
Die mittlere Länge eines Gens ist 989,15 Basen, also etwa eine Kilobase.
#+end_export
#+begin_src bash <<gene.sh>>=
  awk '{l=$2-$1+1; print l}' gene.txt |
      var
#+end_src
#+begin_export latex
\begin{verbatim}
# File Avg    Var    SD     n
stdin  989.15 644071 802.54 566
\end{verbatim}
#+end_export
#+begin_export latex
Wir können auch die Verteilung der Genlängen in Basenpaaren
(\emph{base pairs}, bp) als Histogramm in Abbildung~\ref{fig:his}
plotten. Dort sehen wir, dass die Verteilung der Genlängen durch
extrem lange Gene geprägt ist.
\begin{figure}
  \begin{center}
    \includegraphics{../gene/hist}
  \end{center}
  \caption{Die Verteilung von Genlängen im Genom von \emph{M. genitalium}.}\label{fig:his}
\end{figure}
#+end_export
#+begin_src bash <<gene.sh>>=
  awk '{l=$2-$1+1; print l}' gene.txt |
      histogram |
      plotLine -x "Laenge (bp)" -y "Anzahl"
#+end_src
#+begin_export latex
\section{Gene darstellen}
Bisher sind unsere Gene nur Intervalle auf dem plus oder minus Strang
der DNA. Jetzt wollen wir diese Intervalle sichtbar machen. Wir fangen
mit dem ersten Gen in \ty{gene.txt} an, das auf dem Plus-Strang liegt.
#+end_export
#+begin_src bash <<gene.sh>>=
  head -n 1 gene.txt
#+end_src
#+begin_export latex
\begin{verbatim}
686	1828	+
\end{verbatim}
Wir verwenden das Programm \ty{malGene.awk}, um solche Koordinaten als
Rechtecke zu malen. Der Suffix \ty{awk} im Namen von \ty{malGene.awk}
bedeutet, dass es ein Programm in der Programmiersprache Awk ist. Wir
schauen uns seinen Code an, nur um festzustellen, dass es lesbarer
Text ist---wie unsere kleineren Awk Programme bisher.
#+end_export
#+begin_src bash <<gene.sh>>=
  cat malGene.awk
#+end_src
#+begin_export latex
\begin{verbatim}
{
    start = $1
    ende = $2
    strang = $3
...
}
END {
    printf "1\t0\n"
}
\end{verbatim}
#+end_export
#+begin_export latex
Wir verwenden \ty{malGene.awk}, um unser erstes Gen als Rechteck zu
malen. Dieses besteht aus vier x/y Koordinaten, die vier Ecken eines
Rechtecks. Die fünfte und letzte Position, $(1,0)$, ist unser
Ausgangspunkt.
#+end_export
#+begin_src bash <<gene.sh>>=
  head -n 1 gene.txt |
      awk -f malGene.awk
#+end_src
#+begin_export latex
\begin{verbatim}
686	0
686	1
1828	1
1828	0
1	0
\end{verbatim}
#+end_export
#+begin_export latex
Diese Koordinate können wir mit \ty{plotLine} plotten und erhalten
Abbildung~\ref{fig:gene}A.
\begin{figure}
  \begin{center}
  \begin{tabular}{cc}
  \textbf{A} & \textbf{B}\\
  \scalebox{0.7}{\includegraphics{../gene/gene1}} &
  \scalebox{0.7}{\includegraphics{../gene/gene2}}
  \end{tabular}
  \end{center}
  \caption{Erster Versuch, ein Gen zu plotten (\textbf{A}), und zweiter Versuch (\textbf{B}).}\label{fig:gene}
\end{figure}
#+end_export
#+begin_src bash <<gene.sh>>=
  head -n 1 gene.txt |
      awk -f malGene.awk |
      plotLine
#+end_src
#+begin_export latex
Abbildung~\ref{fig:gene}A ist etwas schwer zu verstehen: Die
Beschriftung der y-Achse ist überflüssig, und die obere und unter
Linie des Rechtecks ist verdeckt. Um sie zu verbessern, lassen wir die
Beschriftung der y-Achse (\ty{-u}) weg und verlängern die y-Achse
(\ty{-Y}). Da Gene auf dem negativ-Strang nach unten gezeichnet
werden, spiegeln wir die y-Achse zusätzlich nach unten. Zuletzt
beschriften wir die x-Achse (\ty{-x}) und erhalten
Abbildung~\ref{fig:gene}B.
#+end_export
#+begin_src bash <<gene.sh>>=
  head -n 1 gene.txt |
      awk -f malGene.awk |
      plotLine -u y -Y "-5:5" -x "Position (bp)"
#+end_src
#+begin_export latex
Jetzt plotten wir alle Gene.
#+end_export
#+begin_src bash <<gene.sh>>=
  awk -f malGene.awk gene.txt |
      plotLine -u y -Y "-5:5" -x "Position (bp)"
#+end_src
#+begin_export latex
Die Position in einzelnen Basen entlang der x-Achse sind schwer zu
lesen.  Wir würden sie statt in Basen gerne in Kilobasen messen. Das
machen wir auch mit Awk.
#+end_export
#+begin_src bash <<gene.sh>>=
  awk '{print $1/1000, $2/1000, $3}' gene.txt |
      head
#+end_src
#+begin_export latex
\begin{verbatim}
0.686 1.828 +
1.828 2.76 +
2.845 4.797 +
4.812 7.322 +
7.294 8.547 +
8.551 9.183 +
9.156 9.92 +
9.923 11.251 +
11.251 12.039 +
12.068 12.724 +
\end{verbatim}

Wir malen die Koordinaten der Gene als Kästchen und plotten sie, um
Abbildung~\ref{fig:genome} zu bekommen.
\begin{figure}
  \begin{center}
    \includegraphics{../gene/genome}
  \end{center}
  \caption{Die 546 Gene von \emph{M. genitalium}.}\label{fig:genome}
\end{figure}
#+end_export
#+begin_src bash <<gene.sh>>=
  awk '{print $1/1000, $2/1000, $3}' gene.txt |
      awk -f malGene.awk |
      plotLine -u y -Y "-5:5" -x "Position (kb)"
#+end_src
#+begin_export latex
Wir können die eben erstellte Abbildung auch in einer Datei speichern,
zum Beispiel \ty{genomPlot.eps}. Der Suffix \ty{eps} zeigt an, dass die
Datei im ``encapsulated Postscript'' Format ist.
#+end_export
#+begin_src bash <<gene.sh>>=
  awk '{print $1/1000, $2/1000, $3}' gene.txt |
      awk -f malGene.awk |
      plotLine -u y -Y "-5:5" -x "Position (kb)" -p genomPlot.eps
#+end_src
#+begin_export latex
Eine Postscript Datei lässt sich auch gut in eine Textdatei
einbinden. Wir verwenden dazu die Datei \ty{text.tex}. Der Suffix
\ty{tex} zeit an, dass es sich dabei um eine Datei für das
Setzprogramm \LaTeX{} handelt. Wir schauen sie uns an.
#+end_export
#+begin_src bash <<gene.sh>>=
  cat text.tex
#+end_src
#+begin_export latex
\begin{verbatim}
\documentclass{article}
\usepackage{graphics}
\usepackage[german]{babel}
\begin{document}

\title{Meine erste \LaTeX{} Datei}
\author{Beatriz Vieira Mourato}
\maketitle

\begin{center}
  \includegraphics{genomPlot}
\end{center}

\end{document}
\end{verbatim}

In der \LaTeX{} Datei fallen besonders die mit Rückstrichen markierten
Wörter auf. Das sind \LaTeX{} Befehle. Zum Beispiel läd der Befehl
\begin{verbatim}
\includegraphics{genomPlot}
\end{verbatim}
unsere Graphik.

Wir setzen die Datei als PDF.
#+end_export
#+begin_src bash <<gene.sh>>=
  pdflatex text
#+end_src
#+begin_export latex
Wir schauen das neue PDF an.
#+end_export
#+begin_src bash <<gene.sh>>=
  evince text.pdf &
#+end_src
#+begin_export latex
\section{Wie geht es weiter?}
\subsection*{\LaTeX{}}
Wer mag, kann weiter mit \ty{text.tex} spielen und zum Beispiel
Folgendes probieren:
\begin{enumerate}
  \item Das Histogramm in Abbildung~\ref{fig:his} in \ty{text.tex}
    einbinden.
  \item Kommentare fangen mit \verb+%+ an. Was passiert, wenn du die
    Zeile
\begin{verbatim}
\usepackage[german]{babel}
\end{verbatim}
auskommentierst?
\item Abbildungen haben die Struktur
\begin{verbatim}
\begin{figure}
   \begin{center}
      \includegraphics{meineGraphik}
   \end{center}
   \caption{Dies ist meine Lieblingsgraphik.}
\end{figure}
\end{verbatim}
Kannst du deine beiden Graphiken in \ty{text.tex} in Abbildungen
umwandeln?
\item Wenn wir im Text auf eine Abbildung verweisen wollen, müssen wir
  die \ty{figure} mit \verb+\label{b}+ beschriften, wobei \ty{b} eine
  beliebige Beschriftung ist. Wenn die Beschriftung gesetzt ist, können
  wir im Text auf sie mit \verb+\ref{b}+ verweisen. Kannst du auf
  deine beiden Abbildungen im Text verweisen?
\end{enumerate}
Wer sich weiter für \LaTeX{} interessiert und Bücher mag, kann das
Buch seines Autors Leslie Lamport lesen~\cite{lam94:lat}. Online
empfehlen wir das Tutorat von Overleaf.
\begin{verbatim}
https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes
\end{verbatim}

\subsection*{Genomik}
Wer Lust auf Genomik auf der Befehlszeile bekommen hat, der kann im
Buch \emph{Bioinformatics for Evolutionary Biologists}
weitermachen~\cite{hau23:bio}.
#+end_export
